name: Generate coverage report

on:
  push:
    branches:
    - main

jobs:
  generate_coverage:
    name: Generate Coverage Report

    permissions:
      contents: write
      pages: write
      id-token: write

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Conda
        uses: actions/cache@v1
        with:
          path: /usr/share/miniconda
          key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}
          restore-keys: |
            ${{ runner.os }}-conda-

      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: 3.9
          conda-channels: anaconda, conda-forge

      - name: Conda install dependencies
        run: conda install fiona==1.9.4

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --force-reinstall -e ".[dev]"

      - name: Test with pytest and generate coverage report
        run: |
          python3 -m coverage run --source=src/geodense -m pytest -v tests
          python3 -m coverage html -d htmlcov
          python3 -m coverage json -o htmlcov/coverage.json
          python3 util.py gen-cov-badge htmlcov/coverage.json htmlcov/badge.json
          ls -lah htmlcov

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: htmlcov # The folder the action should deploy.
          branch: coverage-report
