name: Generate coverage report
on:
  push:
    branches:
      - main
jobs:
  generate_coverage:
    name: Generate Coverage Report
    permissions:
      contents: write
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          # Install a specific version of uv.
          version: "0.4.19"
      - name: Install dependencies
        run: |
          uv sync
      - name: Set env PATH
        run: echo "PATH="$(pwd)/.venv/bin:$PATH"" >> $GITHUB_ENV
      - name: Set env PROJ_DIR
        run: echo "PROJ_DIR="$(pwd)/.venv/lib/python${PYTHON_VERSION}/site-packages/pyproj/proj_dir/share/proj"" >> $GITHUB_ENV
      - name: Test with pytest and generate coverage report
        run: |
          coverage run --source=src/geodense -m pytest -v tests
          coverage html -d htmlcov
          coverage json -o htmlcov/coverage.json
          uv run python3 util.py gen-cov-badge htmlcov/coverage.json htmlcov/badge.json
          ls -lah htmlcov
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: htmlcov # The folder the action should deploy.
          branch: coverage-report
