name: Generate coverage report

on:
  push:
    branches:
    - main

jobs:
  generate_coverage:
    name: Generate Coverage Report | python=${{ matrix.python-version }}
    
    permissions:
      contents: read
      pages: write
      id-token: write
      
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge

      - name: Conda install dependencies
        run: conda install fiona==1.9.4

      - name: Install dependencies
        run: |
          python${{ matrix.python-version }} -m pip install --upgrade pip
          python${{ matrix.python-version }} -m pip install --force-reinstall -e ".[dev]"

      - name: Test with pytest and generate coverage report
        run: |
          python${{ matrix.python-version }} -m coverage run --source=src/geodense -m pytest -v tests
          python${{ matrix.python-version }} -m coverage html -d ./htmlcov
          python${{ matrix.python-version }} -m coverage json -o ./htmlcov/coverage.json
          python${{ matrix.python-version }} util.py gen-cov-badge ./htmlcov/coverage.json ./htmlcov/badge.json
          ls -lah ./htmlcov

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: htmlcov # The folder the action should deploy.
          branch: coverage-report
