name: Run linting, type check and unit tests
on:
  pull_request:
jobs:
  linting_and_tests:
    name: Linting, Type Check and Tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          # Install a specific version of uv.
          version: "0.4.20"
      - name: Install dependencies
        run: |
          uv sync
      - name: Set env PATH
        run: echo "PATH="$(pwd)/.venv/bin:$PATH"" >> $GITHUB_ENV
      - name: Set env PROJ_DIR
        run: echo "PROJ_DIR="$(pwd)/.venv/lib/python${PYTHON_VERSION}/site-packages/pyproj/proj_dir/share/proj"" >> $GITHUB_ENV
      - name: Lint with ruff
        run: |
          ruff check -v .
      - name: Run Mypy
        run: |
          mypy src/
      - name: Test with pytest and generate coverage report
        run: |-
          coverage run --source=src/geodense -m pytest -v tests
