name: Run linting and unit tests

on:
  pull_request:

jobs:
  linting_and_tests:
    name: Linting and Tests | python=3.9
    env:
      PROJ_DATA: /usr/share/miniconda/share/proj
      PROJ_NETWORK: ON
    defaults:
      run:
        shell: bash -l {0}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          channels: conda-forge
          channel-priority: flexible
          auto-activate-base: true
          activate-environment: myenv


      - name: Set environment variables used in cache
        run: |
          echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Cache Mamba
        id: cache
        uses: actions/cache@v3
        env:
          CACHE_NUMBER: 0 # Increment this number if you wish to hard-refresh the cache.
        with:
          path: /usr/share/miniconda/envs/myenv
          key: conda-${{ env.DATE }}-${{ env.CACHE_NUMBER }}

      - name: Install development dependencies (if invalid cache)
        run: conda install -n myenv fiona==1.9.4
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Install dependencies
        run: |
          conda activate myenv
          python3 -m pip install --upgrade pip
          python3 -m pip install --force-reinstall -e ".[dev]"

      - name: Lint with black
        run: |
          conda activate myenv
          python3 -m black --check .

      - name: Lint with ruff
        run: |
          conda activate myenv
          python3 -m ruff -v .

      - name: Test with pytest and generate coverage report
        run: |
          conda activate myenv
          python3 -m coverage run --source=src/geodense -m pytest -v tests
