name: Run linting and unit tests

on:
  pull_request:

jobs:
  docker_tests:

    runs-on: ubuntu-latest
    name: Linting and Tests | python=${{ matrix.python-version }}
    env:
      DEBIAN_FRONTEND: noninteractive
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        # python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge

      - name: Conda install dependencies
        run: conda install fiona==1.9.4

      - name: Install dependencies
        run: |
          python${{ matrix.python-version }} -m pip install --upgrade pip
          python${{ matrix.python-version }} -m pip install --force-reinstall -e ".[dev]"

      - name: Lint with ruff
        run: |
          python${{ matrix.python-version }} -m ruff -v .

      - name: Test with pytest
        run: |
          python${{ matrix.python-version }} -m pytest -v tests
